language: node_js
node_js:
  - 10
  - 11
  - 12
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add codecov istanbul
install:
  - yarn
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
  - yarn run lint
  - docker build --pull -t "${IMAGE_NAME}" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  - docker push "${IMAGE_NAME}"
notifications:
  slack:
    rooms:
      - araytek:B8Xevy6shC51ftn3tBiZR8fw
    on_success: change
    on_failure: always
branches:
  only:
    - master
    - "/^greenkeeper.*$/"
env:
  global:
    secure: "hegKmc08gxX+kap5wQH81LB9DQiRFsV+AUazd/Tyl52+JBCoDFlIii3Zs0+RbaYDfwI1m6UnrTvwEKRQOLrck3sosD8GI7v8kzWarTJYVi2DD+2HBVMoUi4s6UNVnIhk1mQeFc61KasaNVtb1mWSnsQD7XLaSA6hUyZhNOTJxIsQfPk4YxbQCuh7DdaEwC4/0Y4y1upTE2PqRz09Unmk0KCf9EqmDhb+P0THrBWBhIEa7uH0FXF+n0fwProYKm0PQ9nzOH9+cYwWM5rhVKQx2SgY6ePxOZQaj+4CIjml4eQjFLizdsCNPf0L/lxRAmWOwdKDnO3n606SQ2XfCx3hfyNTbWqFgeaJYSGFSduLAyTfQX+na+6B5v0ogvQilQwe0312OabQx4rFZCBEw02b7HMDKxFvCgOX7LZK48mtq5bcQrhPX7yqnwYpOBhcohTFEjTpFPmA+NCE3vt6mcnS2l9GvsSFIYW+cq/2kUzRIC9PZ7ZkamPoFcQXKK3gTs9eNMa+lRILwcD+bzlcttzvBgMm4/Ah8/Zba6JQcLDBw4MtcJPhm76cNtZ4hQMuF7sAW4wwXXdl0SZou0fH+3XfvZvg97XbHaCyrR3C0goQ8/6BgxEZ+ivv7ZLQzQKYpiT4JJirl81rIHZp53fQPx23/dt4Z0P4UEx7HFNiW0opeqA="
    - PROJECT_NAME: osk2/gogo-cash-rebate
    - IMAGE_NAME: ${PROJECT_NAME}:${TRAVIS_COMMIT:0:8}
